---
abstract: 'detect and/or install zeromq'
author:
  - 'Charles McGarvey <chazmcgarvey@brokenzipper.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Archive::Tar: 0
  Cwd: 0
  Digest::SHA: 0
  File::Path: 0
  File::Spec::Functions: 0
  IPC::Cmd: 0
  LWP::Simple: 0
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-ZMQ
requires:
  strict: 0
  warnings: 0
version: 0.02
